### ISSUE TITLE
Реализовать базовую версию ASP Net приложения

### ISSUE THREAD

**Issue by iliadzen** [MindboxDevSchool/MindhubDevTeam#33]
Создание базового проекта в солюшене и первичная конфигурация

**Comment by thegreatdeveloper** [comment]
- [ ] UserService
- [ ] TrackerService
- [ ] EventService

**Comment by SilkSlime** [comment]
# Сначала допилить все сервисы в мастер

**Comment by iliadzen** [comment]
> # Сначала допилить все сервисы в мастер

Само собой
